#github action

name: deploy and invalidate cloudfront cache

on:
  push:
    branches:
      - main

jobs:
  deploy-and-invalidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync S3
        uses: jakejarvis/s3-sync-action@master
      
      - name: Invalidate Cloudfront cache
        uses: chetan/invalidate-cloudfront-action@v2
    
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_s3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
      AWS_REGION: 'us-east-1'
      PATHS: "./src"
      SOURCE_DIR: '/'
